coverage:
  status:
    project:
      default:
        target: auto # auto compares coverage to the previous base commit
        threshold: 1% # fail if coverage drops by more than 1%

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    statuses:
      - type: project
        target: auto
        threshold: 1%
      - type: patch
        target: 90%
