source 'https://rubygems.org'

gem "jekyll", "4.3.2"

gem 'jekyll-redirect-from', "0.16.0"

gem 'jekyll-relative-links', "0.7.0"

gem 'jekyll-titles-from-headings', '0.5.3'

gem "just-the-docs", "0.7.0"
