source 'https://rubygems.org'

gem "jekyll", "4.3.2" # installed by `gem jekyll`
# gem "webrick"        # required when using Ruby >= 3 and Jekyll <= 4.2.2

gem 'jekyll-titles-from-headings', '0.5.3'

gem "just-the-docs", "0.7.0" # pinned to the current release
