name: "Chromatic Publish"

on: push

# Add required environment variables to satisfy build, they are blank as the relevant dependencies are mocked
env:
  DATABASE_URL: ""
  SUPERTOKENS_API_KEY: ""
  SUPERTOKENS_CONNECTION_URI: ""

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@c9067691aca4a28d6fbb40d9eea6e144369fbcae # v10
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
