name: "Chromatic Publish"

on: push

# Add required environment variables to satisfy build, they are blank as the relevant dependencies are mocked
env:
  DATABASE_URL: ""
  SUPERTOKENS_API_KEY: ""
  SUPERTOKENS_CONNECTION_URI: ""

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version-file: "package.json"
          cache: "npm"
      - run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@v10
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
