name: "Chromatic Publish"

on: push

# Add required environment variables to satisfy build, they are blank as the relevant dependencies are mocked
env:
  DATABASE_URL: ""
  SUPERTOKENS_API_KEY: ""
  SUPERTOKENS_CONNECTION_URI: ""

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4
        with:
          node-version-file: "package.json"
          cache: "npm"

      - run: corepack enable
      - run: npm ci

      - name: Publish to Chromatic
        uses: chromaui/action@c6e348fcea252c75f99c90db328cc5c98a7dd534 # v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          exitOnceUploaded: true
