name: Delete Preview Environment Variables

env:
  VERCEL_ACCESS_TOKEN: ${{ secrets.VERCEL_ACCESS_TOKEN }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  delete:
    runs-on: ubuntu-latest
    steps:
      - uses: snaplet/vercel-action@v3.0.1
        with:
          delete: true
